Реализовал основу для нейросети.
K1ngNothing/Neural-Networks-from-Scratch pull request #1
Opened 2023-04-27 09:38 UTC by K1ngNothing

На данный момент реализованы основные компоненты нейросети (думаю названия компонент говорят сами за себя, не вижу смысла повторяться).

То, что на данный момент реализованно и что то что нужно реализовать:
* Model: конструктор, обучение по одному вектору, предсказание по вектору / набору векторов, оценка эффективности (делаются предсказания по тестовой выборке, а потом сравниваются правильные ответы с предсказаниями и считается средняя ошибка)
* Layer: пуш вектора / градиента, обновление параметров сети. Последнее реализовано так, что при обучении накапливаются изменения параметров, а при вызове ApplyChanges они единовременно применяются (сделано с прицелом на обучения батчами)
* SigmaFunction: стирающий тип, предназначенный для нелинейной компненты слоя. Также реализованы Sigmoid и ReLU функции, которыми пользователь может пользоваться из коробки.
    Для кастомных сигма-функций достаточно реализовать класс с операторами () для вычисления функции и [] для вычилсения производной.

То, что на данный момент НЕ реализованно и что то что нужно реализовать:
* Разбивать обучающую выборку на батчи: на данный момент Train втупую берет по одному вектору, обучает по нему нейросеть, и сразу применяет изменения. В идеале она должна как-то побить данные на батчи, прогнать батч целиком, и только потом применить изменения параметров. Причина, почему пока сделано так: я не особо пока чекал МЛ-е гайды и просто не уверен, как это по-нормальному делать.
*

2023-05-01 17:48 UTC, DimaTrushin requested changes
- Прошелся по коду. Основная проблема -- ты не заботишься о копировании или перемещении данных. Все аргументы функции у тебя принимают by valuex -- это плохо для тяжелых данных. Я там написал в паре мест что не так и как надо менять. Но ты потом по аналогии сделай это везде. Кратко тяжелые данные передаем const T& встроенные типы и мелкие POD типы передаем by value.
- Мне не нравится глобально конструктор сети.
- И еще с названиями беда.

2023-05-01 17:48 UTC, DimaTrushin commented on CMakeLists.txt
> +               )
Не радуй читателя твоего репозитория "кирпичами" с гитхаба. Делай пустую строку в конце каждого файла.

2023-05-01 17:48 UTC, DimaTrushin commented on main.cpp
> +std::vector<TrainingPair> generate_data_set(size_t vec_size, size_t set_size) {
Когда определяешь функции (переменные или классы) в cpp файле помещай их в anonymous namespace. Иначе у тебя может быть коллизия при линковке. Возьми это за правило.

2023-05-01 17:48 UTC, DimaTrushin commented on main.cpp
> +std::vector<TrainingPair> generate_data_set(size_t vec_size, size_t set_size) {
Кроме того, вынеси весь тестовый код в отдельную единицу трансляции. А в main только делай вызовы нужных функций.

2023-05-01 17:48 UTC, DimaTrushin commented on main.cpp
> +using namespace model::dist_functions;
Вот так лучше не делать.
Я думаю, что тут беда в том, что у тебя вложенные пространства имен и не понято мне пока зачем это надо было делать. Ну и можно было псевдонимы ввести двухбуквенные как в питоне для numpy делают np. Или поместить эти юзинги внутрь каждой функции, где ты используешь. Или сделать анонимное пространство имен и там сделать эти юзинги, чтобы ничего не утекало в глобальное пространство имен.

2023-05-01 17:48 UTC, DimaTrushin commented on main.cpp
> +        set.emplace_back(vec, res);
Ты передаешь lvalue в emplace_back. Это бессмысленно. У тебя тут происходит ненужное копирование. Надо поставить std::move вокруг vec и res.

2023-05-01 17:48 UTC, DimaTrushin commented on main.cpp
> +        model.Train(training_set, EuklideanSquaredDist(), std::function(modifier_func));
Если это тренировка, то надо понимать, что ты на каждом векторе тренируешься ни один раз. Ты по тренировочному множеству должен уметь пройтись несколько раз -- это число называется количеством эпох. Его надо уметь указывать (то есть максимальное число эпох). Кроме того, ты тут смотришь на последнюю ошибку, а вообще говоря хорош бы указывать на какой ошибке остановиться, типо мы либо останавливаемся после 1000 эпох, либо если ошибка упала ниже такой-то.

2023-05-01 17:48 UTC, DimaTrushin commented on main.cpp
> +    double avg_error = model.AssessEffectiveness(testing_set, EuklideanSquaredDist());
А почему это называется effectiveness?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
Вообще эта хрень называется Activation Function

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +            value_ = std::move(value);
Конструктор должен строить объект в списке инициализации
```cpp
Inner(T value) : value_(std::move(value)) {}
```

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +        virtual Vector operator()(Vector x) = 0;
- Не уверен, что это хорошая идея принимать вектор by value. Это копирование вектора, учитывая, что ты внутри не муваешь это проблема, а так это непредвиденная для пользователя накладка на расходы. Я бы сделал const Vector&. Либо если хочешь иметь две версии, то сделай две версии const Vector& и Vector&& и у второго делай мувы.
- Почему оператор не константный? Ты кешируешь какие-то данные?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +        virtual ~InnerBase() {
Сделай конструктор protected, чтобы его нельзя было вызвать через указатель на базу.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +        T value_;
value_ плохое название, у тебя же это конкретный функциональный объект, лучше назвать function_ или smooth_function_

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +    }
- Если ты хочешь тут принимать value по значени, то в конструкторе Inner можно принимать данные по rvalue reference, чтобы сэкономить один мув.
- Кроме того, надо пользоваться списком инициализации
```cpp
SigmaFunction(T value) : ptr_(std::make_unique<Inner<T>>(std::move(value)));
```

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +    }
Не делай такой оператор. Конструируй именно конструктором, а не оператором равенства. Кроме того, в этом случае лучше было бы сделать что-то вроде return *this = SigmaFunction(std::move(value)); Но лучше убрать.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +        return (*ptr_)(x);
опять же у тебя куча ненужных копирований, либо const Vector& x, либо (*ptr)(std::move(x)). Но я бы предпочел первое, либо еще rvalue reference.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +    std::unique_ptr<InnerBase> ptr_;
Не уверен, что ptr_ хорошее название. Но пусть остается.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +namespace sigma_functions {
А зачем отдельный namespace?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +namespace model {
А почему namespace называется model?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/sigma_function.h
> +};
Судя по тому, что я вижу, у тебя есть класс, который принимает две функции f и f' и по ним определяет два оператора. Может быть это стоит обернуть в шаблонную оболочку, чтобы пользоваться так
```cpp
template<class Func, class Der>
class SmoothFunction {
...
};
```
Или может быть даже не делать так, а сделать именной конструктор в ActivateFunction (которая у тебя SigmaFunction).
```cpp
class SigmaFunction {
...
template<class Func, class Der
static FromFunction(Func&& function, Der&& derivative) {
  SigmaFunction f;
  // initiate f
  return f;
}
...
};
```
Тогда можно пользоваться
```cpp
auto x = SigmaFunction::FromFunction(func, deriv);
```
Ну и можно именные конструкторы сделать для сигмоида и релу.

Тут было много слов, но у тебя явно ReLU и Sigmoid -- это один и тот же класс, в котором заданы две разные функции для вычисления координаты и производной.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +    }
Во-первых, я не уверен, что эти два конструктора не могут быть ambiguous.
Во-вторых, тебе достаточно только одного из них и я бы выбрал второй.
В-третьих, у структур есть aggregate initialization вобход вызова конструктора, а в c++20 у него еще и именованные поля, что удобнее использовать. Потому я бы убрал вообще эти конструкторы.
https://en.cppreference.com/w/cpp/language/aggregate_initialization

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +        Layer() = default;
Ты уверен, что ты хочешь дефолтный конструктор без дефолтных размеров для A_ и b_? Это же неработающий слой. И у тебя нет возможности его потом перенастроить. Так что я бы убрал этот конструктор.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +    public:
Все тяжелые аргументы передавай по константной ссылке, все встроенные типы by value.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +    class Layer {
А почему Layer определил внутри модели? Почему не вынести?
UPD: вынеси в отдельный header и положи в папку Layer.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +          sigma_functions::SigmaFunction sigma);
Я честно, не глядя в тело конструктора, сейчас не понимаю, что у тебя строится. Например, я строю сеть с входным слоем указанного размера, выходным слоем указанного размера, всего слоев cnt_layers (? если да, то надо как-то по-другому назвать), и потом во всех слоях у тебя сигма одна и та же?
Я бы ожидал список сигм и размеров каждого слоя. Какой размер у промежуточных слоев?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +    std::vector<Vector> PredictBatch(std::vector<Vector> data);
Не делай вектор векторов. Работай с матрицами.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +                               dist_functions::DistanceFunction dist);
Вот эта функция мне не ясна.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +                 dist_functions::DistanceFunction dist_func,
Я правильно понимаю, что dist_func -- это функция штрафа, то есть она должна уметь вычислять разницу на  значениях и начальный градиент по входу? Названия плохие, все в сокращениях.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +    assert(cnt_layers > 0 && "Model constructor: count of layers should be at least 1");
Так это не количество всех слоев, это количество внутренних слоев?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +    std::vector<Layer> layers_;
Зачем хранить Layers_count_? Чем он отличается от размера Layers_?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +        layers_[i] = std::move(Layer(input_size, input_size));
- Вот, это мне не нравится, я бы тут ожидал разные слои.
- Как такое делать.
1) Сначала надо зарезервировать память под слои, то есть ты в списке инициализации не создаешь вектор нужного размера. Ты просто оставляешь его неинициализированным (пустой вектор).
2) Потом ты делаешь layers_.reserve(cnt_layers); или сколько тебе надо.
3) Потом ты делаешь layers_.emplace_back(...); и вот тут вставляешь все слои.
Если тебе надо вставить несколько слоев сразу, то надо делать по аналогии с примером ниже
```cpp
class A {
  template<class... TArgs>
  A(TArgs&&... args) {
    vec_.reserve(sizeof...(TArgs));
    auto i = {(vec_.emplace_back(std::forward<TArgs>(args)), 0)...};
    //    auto i = {vec_.emplace_back(std::forward<TArgs>(args))...};
    (void)i;
  }
  std::vector<int> vec_;
};
```

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.h
> +public:
Зачем повторять public?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +double Model::TrainOnePair(TrainingPair training_pair, dist_functions::DistanceFunction dist,
У тебя функции в h и cpp в разном порядке. Так быть НЕ должно.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +                           double modifier) {
Что за modifier? Как я должен по названию понять в чем суть этой переменной?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +    Vector x = training_pair.input;
копирование

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +    for (size_t i = 0; i < layers_count_; i++) {
for (auto& layer : layers_)
  x = layer.PushVector(x);

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +    for (ssize_t i = layers_count_ - 1; i >= 0; i--) {
здесь можно попытаться сделать for (auto& layer : ...) используя reverse_iterator

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +        u = new_grad;
new_grad не нужен, ты можешь сразу писать
u = layers_[i].PushGradient(u);

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +        i++;
Зачем тебе тут i?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +    for (const TrainingPair& pair : training_data) {
Ты всего один раз проходишь по данным. Это плохо, надо проходить до тех пор, пока ты либо не превысил количество эпох, которое допустимо, либо пока точность не упала ниже заданной.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/model.cpp
> +        result.emplace_back(std::move(Predict(data[i])));
Когда делаешь move нет смысла делать emplace_back, это равносильно push_back. Только если ты передаешь аргументы конструктора есть смысл делать emplace_back.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/Layer/layer.cpp
- Раз у тебя свой cpp файл под Layer, то сделай и отдельный header.
- Кроме того, тут не очевидно, где искать header.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/Layer/layer.cpp
> +    b_ = Vector::Random(m);
- Эти рандомы в Eigen не самые лучшие. Они дают равномерное распределение. Есть возможность использовать другие через еще один доп пакет
https://bab2min.github.io/eigenrand/v0.5.0/en/index.html
- Кроме того, почему ты не используешь списки инициализации? Тут можно писать
```cpp
Layer::Layer(size_t m, size_t n) : A_(Matrix::Random(m, n)), ... {}
```

2023-05-01 17:48 UTC, DimaTrushin commented on Model/Layer/layer.cpp
> +RowVector Model::Layer::PushGradient(RowVector u) {
Как я вижу, эта функция не безопасная, она подразумевает, что до нее PushVector вызывали. Это плохая точка дизайна. Только если ты что-то оптимизируешь это может быть хорошо. Пусть пока так остается, надо подумать, как сделать лучше.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/Layer/layer.cpp
> +    b_ += delta_b_;
Еще бы хорошо хранить количество раз изменений delta, чтобы перед этой операцией усреднить. То есть если в delta_A_ прибавилось k градиентов, то ты тут хочешь сделать A_ += delta_A_ / k;

2023-05-01 17:48 UTC, DimaTrushin commented on Model/SigmaFunction/relu.cpp
> +}
Повторение кода с Sigmoid

2023-05-01 17:48 UTC, DimaTrushin commented on Model/DistanceFunction/distance_function.h
> +class DistanceFunction {
Плдохое название. Это функция штрафа.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/DistanceFunction/distance_function.h
> +    std::shared_ptr<InnerBase> ptr_;
Нахуя shared_ptr??? Какого хуя? Сделать unique_ptr.

2023-05-01 17:48 UTC, DimaTrushin commented on Model/DistanceFunction/distance_function.h
> +namespace dist_functions {
Зачем тут еще один namespace?

2023-05-01 17:48 UTC, DimaTrushin commented on Model/DistanceFunction/distance_function.h
По сути у тебя в начале определяется стирающий тип. Это хорошо. Но потом ты определяешь конкретную функцию. Думаю, что код для стирающего типа надо в отдельный header + cpp, а уже конкретные функции для ошибки делать в отдельной паре h/cpp.
Аналогично для стирающих типов для пороговой функции (ActivationFunction, которые у тебя SigmaFunction).

2023-05-04 12:51 UTC, K1ngNothing commented on Model/model.h
> +public:
Я так отделяю конструкторы от методов (по-моему в Яндексе так же делали)

2023-05-05 13:52 UTC, K1ngNothing commented on Model/SigmaFunction/sigma_function.h
> +        virtual ~InnerBase() {
Не понял если честно, у InnerBase же нет конструктора... (да и не может быть, потому что это виртуальный класс) Да и вообще, protected разве нужен не для того, чтобы какие-то методы базового класса, которые мы бы хотели сделать private, можно было использовать в классах-наследниках? Тогда в принципе не понятно, что можно было бы сделать protected (у меня все методы public)

2023-09-27 09:56 UTC, closed without merging