Реализовал задачу распознавания цифр по картинке (database MNIST).
K1ngNothing/Neural-Networks-from-Scratch pull request #2
Opened 2023-05-09 10:00 UTC by K1ngNothing

Собсвтвенно все сказано в названии pr)
За ночь обучения с параметрами, указанными в pr, получилось достичь 99% точности на обучающей выборке и 94% точности на тестовой выборке (за 10 эпох обучения). Пока что особо не запаривался над обучением, потому что пока не реализовал сохранение слоев. 

Сначала стоит глянуть предыдущий pr (dev -> main, "Реализовал основу для нейросети"), а потом уже этот.

2023-05-16 15:10 UTC, DimaTrushin requested changes
Выглядит неплохо. Есть некоторые косяки, на которые я указал.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +        virtual std::unique_ptr<InnerBase> Clone() const = 0;
Я бы этот метод сделал приватным, чтобы никто снаружи через базу не мог его явно вызвать. Это деталь имплементации.
UPD Увидел, что ты не даешь эту штуку наружу, так что ОК, можно и так оставить.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +        virtual ~InnerBase() {
Сделай
virtual ~InnerBase() = default;
И сделай его protected.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +    ActivationFunction(const ActivationFunction& other) : ptr_(other.ptr_->Clone()) {
Вот эта имплементация упадет, если other.ptr_ == nullptr, тут надо вставить проверку, что other не пуст. А такое может быть, если ты из него мувнул.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +    ActivationFunction(ActivationFunction&& other) : ptr_(std::move(other.ptr_)) {
сделай
```cpp
ActivationFunction(ActivationFunction&& other) noexcept = default;
```

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +    public:
Не повторяй ключевые слова, которые уже выше указаны.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +    public:
не повторяй

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/predefined.cpp
> +Vector model::impl::ApplyCoordinateWise(const Vector& x, std::function<double(double)> function) {
оберни все в namespace по правилу
```cpp
namespace model {
namespace impl {
  Vector ApplyCoordinateWise(...) {
    ...
  }
}
}
```
Так меньше будет длинных имен и проще код будет читать.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/predefined.h
> +Matrix GetJacobianMatrix(const Vector& x, std::function<double(double)> function);
А почему std::function, а не указатель на функцию? Просто у тебя ж везде только функции используются, потому можно было сделать так
```cpp
Vecor ApplyCoordinateWise(const Vector& x, double(* function)(double));
```
Либо сделать 
```cpp
using Signature = double(double);
using FPtr = Signature*;
Vector ApplyCoordinateWise(const Vector& x, FPtr function);
```

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/predefined.cpp
> +Vector SoftMax::operator()(const Vector& x) const {
Как это компилится, если у тебя в хедере объявлен SoftMax в model, а тут в global namespace?

2023-05-16 15:10 UTC, DimaTrushin commented on Model/Layer/layer.h
> +    Vector PushVector(const Vector& x) const;
А в чем разница? Второй метод не сохраняет кэш? Ты уверен, что это хорошая идея, что так по разному работающие методы имеют одно и то же название?

2023-05-16 15:10 UTC, DimaTrushin commented on Model/Layer/layer.cpp
> +    : A_(Eigen::Rand::normal<Matrix>(output_size, input_size, GetRNG()) * 0.01),
волшебная константа 0.01

2023-05-16 15:10 UTC, DimaTrushin commented on Model/Layer/layer.cpp
> +Layer::Layer(std::ifstream& ifstream, const ActivationFunction& sigma) : sigma_(sigma) {
Мне не очень нравится идея такого конструктора.
1) Это нарушение зоны ответственности. Читать из файла конструктор не должен. Это какой-то другой объект, который конструирует слоя должен делать.
2) Мне не нравится, что ты не сохраняешь функции активации. Можно сделать с enum-ами как я сказал.
3) Как минимум такой конструктор должен делигировать чтение всех данных из потока другому объекту, который умеет возвращать нужные данные и в идеале сразу в списке инициализации их инициализировать. Но видимо лучше иметь конструктор от сохраненных полей.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/Layer/layer.cpp
> +}
Я бы сменил названия. Ибо у тебя методы делают совсем разные вещи. Легко облажаться и сделать не то.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/LossFunction/loss_function.h
> +    LossFunction(const LossFunction& other) : ptr_(other.ptr_->Clone()) {
опять баг

2023-05-16 15:10 UTC, DimaTrushin commented on Model/ActivationFunction/activation_function.h
> +
Если ты определяешь copy constructor, то надо определить и copy assignment, потому что компилятору разрешается его сгенерировать самому и взаимо заменять с copy constructor. В данном случае, у тебя хранится unique_ptr, и copy assignment не будет сгенерирован. Но лучше это сделать. Как и с move assignemnt.
```cpp
ActivateionFunction& operator=(const ActivationFunction& other) {
  return *this = ActivationFunction(other);
}
ActivationFunction& operator=(ActivationFunction&& other) noexcept = default;
```
Вообще. Так можно UB словить.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/LossFunction/loss_function.h
> +    LossFunction(LossFunction&& other) : ptr_(std::move(other.ptr_)) {
Та же фигня с конструкторами и присваиваниями, что в ActivationFunction

2023-05-16 15:10 UTC, DimaTrushin commented on Model/LossFunction/predefined.cpp
> +    assert(y.size() == 1 && answer >= 0 && x(answer) > 0 && "CrossEntropy::operator()");
Что тут за хрень происходит? У тебя что, это только для числовых значений для y определено? и при этом эти значения должны после округления давать числа не больше, чем размер x?

2023-05-16 15:10 UTC, DimaTrushin commented on Model/LossFunction/predefined.cpp
> +    int answer = static_cast<int>(y(0));
Это что за магия?

2023-05-16 15:10 UTC, DimaTrushin commented on Model/model.cpp
> +Model::Model(const std::string& filename,
Тут то же самое замечание, что и про слои.

2023-05-16 15:10 UTC, DimaTrushin commented on Model/model.cpp
> +        if (epoch % 1 == 0) {  // TODO: verbose option
Что тут за дичь?

2023-05-16 15:10 UTC, DimaTrushin commented on Model/model.cpp
> +            std::cout << "stopped at epoch " << epoch << std::endl;
А не надо тут тоже вывести всю информацию и про Loss и learning rate?

2023-05-16 15:10 UTC, DimaTrushin commented on Model/rng.h
> +}  // namespace model
кирпичи

2023-05-16 15:10 UTC, DimaTrushin commented on Model/rng.h
> +static std::mt19937_64& GetRNG() {
А ты хочешь чтобы в каждом cpp файле была своя версия getRNG? Или ты хочешь глобальный единый на все cpp файлы? Если первое, то static -- ОК. Если второе, то лучше убрать static и перенести имплементацию в cpp файл.

2023-05-16 15:10 UTC, DimaTrushin commented on digits_recognition.cpp
В принципе так сойдет. Но в целом, тут у тебя есть функции, которые относятся к объекту читающему из файла. Потом есть глобальные константы относящиеся к эксперименту и потом разные методы относящиеся к эксперименту. Можно было бы оформить объект отвечающий за эксперимент, в нем хранятся все настройки и методы запуска. И их уже вызывать. Но в целом, можно и так оставить.

2023-05-16 15:10 UTC, DimaTrushin commented on example_task.cpp
> +    std::vector<model::TrainingPair> training_set = GenerateDataSet(INPUT_SIZE, 100);
магическая константа 100

2023-05-16 15:10 UTC, DimaTrushin commented on example_task.cpp
> +        model::Vector vector = Eigen::Rand::normal<model::Vector>(vector_size, 1, model::GetRNG());
а что тут значит 1?

2023-05-16 15:10 UTC, DimaTrushin commented on example_task.cpp
> +    for (size_t i = 0; i < 3; i++) {
почему три?

2023-05-16 15:10 UTC, DimaTrushin commented on example_task.h
> +#include <model.h>
Вот это можно внутрь cpp файла перенести.

2023-05-16 15:10 UTC, DimaTrushin requested changes
Выглядит неплохо. Есть некоторые косяки, на которые я указал.

2023-05-17 02:30 UTC, K1ngNothing commented on example_task.cpp
> +        model::Vector vector = Eigen::Rand::normal<model::Vector>(vector_size, 1, model::GetRNG());
Это какая-то рофлянка у Eigen::Rand: если ты хочешь сгенирировать случайный вектор-сотлбец, то недостаточно указать в template-е model::Vector -- все равно нужно указывать размеры матрицы (т.е. vector_size x 1). Единственное, что делает template -- если ты неправильно указал размеры, то сработает асерт.

2023-05-17 02:33 UTC, K1ngNothing commented on example_task.cpp
> +    for (size_t i = 0; i < 3; i++) {
Не, ну можно вынести в константы... Но вообще это число выбрано от балды.

2023-05-17 02:36 UTC, K1ngNothing commented on Model/model.cpp
> +        if (epoch % 1 == 0) {  // TODO: verbose option
Так, ну я забыл поменять константу... (изначально там было 10 и это имело больше смысла). А вообще я хотел сделать опцию verbose, но не особо понял как это реализовать (по этому поводу задавал тебе вопрос в тг).

2023-05-17 02:43 UTC, K1ngNothing commented on Model/LossFunction/predefined.cpp
> +    assert(y.size() == 1 && answer >= 0 && x(answer) > 0 && "CrossEntropy::operator()");
Все так: данная функция потерь применяется в задаче классификации, и предполагается, что y -- это вектор размера 1, который содержит индекс правильного ответа (и соответственно мы хотим штрафовать за то, что у нашей модели низкая уверенность в правильном ответе). Соглашусь, что сделано через жопу, но по-идее это должно работать: double может хранить int без потери точности. Из того, чего здесь не хватает: нужно проверить, что y(0) есть int (добавить асерт answer == y(0)), а также проверить, что answer не выходит за границы вектора x (answer < x.size()). 

Возможно лучше заменить тип y-ка на вектор интов, но у меня смутные сомнения, что из-за этого придется сильно код менять (т.к. у меня абсолютно везде в коде предполагался вектор даблов)

2023-05-17 02:53 UTC, K1ngNothing commented on Model/Layer/layer.cpp
> +Layer::Layer(std::ifstream& ifstream, const ActivationFunction& sigma) : sigma_(sigma) {
1. А почему конструктор не должен читать из потока...? Просто не очень понимаю, почему это нарушает ответственность. Если файл битый или не того формата, то все равно же не получится сконструировать слой. Разве что мы почему-то хотим, чтобы прога падала не в конструкторе, а в какой-то другой вспомогательной функции / классе, но казалось бы, нафига... 

А вообще, в чем прям прелесть списка инициализации? Как я понял, а) иногда без него просто нельзя (например, когда у поля нет дефолтного конструктора б) мы хотим сэкономить дефолтную инициализацию объекта. Но казалось бы в данном случае ни то, ни то не являются проблемой: при дефолтной инициализации матрицы не происходит никаких аллокаций (если я правильно помню документацию к Eigen). Правда ли, что тогда в данном конкретном случае нам пофиг, инициализируем ли мы списком инициализации, или же строим объект внутри конструктора?

2023-05-17 02:59 UTC, K1ngNothing commented on Model/Layer/layer.cpp
> +    : A_(Eigen::Rand::normal<Matrix>(output_size, input_size, GetRNG()) * 0.01),
Ну... она реально волшебная -- просто в книге сказали, что вот так вот хорошо инициализировать (множитель нужен, чтобы коэффициенты не были большими). Можно придумать этой константе какое-то название (например, CORRECTION_FACTOR), но не думаю, что это сделает код более читаемым

2023-05-17 03:01 UTC, K1ngNothing commented on Model/ActivationFunction/predefined.cpp
> +Vector SoftMax::operator()(const Vector& x) const {
Видимо магия using namespace model... но вообще да, сделано не оч

2023-05-17 03:04 UTC, K1ngNothing commented on Model/ActivationFunction/activation_function.h
> +    public:
Ок, уберу. Но разве нельзя использовать повторение ключевых слов, чтобы разделять конструкторы / методы / деструктор? По-моему так в Яндексе делали, или на каком-то из курсов по плюсам (крч не я это придумал). Но в целом да, прям большого смысла в таком повторении нет.

2023-05-17 03:50 UTC, K1ngNothing commented on Model/ActivationFunction/activation_function.h
> +        virtual ~InnerBase() {
С protected не компилиться((( (в лс потом кину больше инфы + сам помедитирую над этим)

2023-09-27 09:54 UTC, merged